import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
 {
    path: '',
    title: '',//Afficher avant l'icon Accueil -- Main
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Accueil',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'Reservation',
    moduleName: 'booking',
    iconType: 'material-icons-two-tone',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/reservation/calendrier',
        title: 'Chambre',
        moduleName: 'reservation',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }, 
      {
        path: '/reservation/menu',
        title: 'Menu',
        moduleName: 'reservation',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
     /* {
        path: '/reservation/test',
        title: '',//new future 
        moduleName: 'reservation',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },*/
    ],
  },
 
  {
    path: '',
    title: 'Stock',
    moduleName: 'stock',
    iconType: 'material-icons-two-tone',
    icon: 'equalizer',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [

      {
        path: 'stock/courses',
        title: 'Courses',
        moduleName: 'stock',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      
        {
          path: 'stock/gestion-stock',
          title: 'Gestion de stock',//
          moduleName: 'stock',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          submenu: [],
        },
        
        {
          path: 'stock/inventaires',
          title: 'Inventaires',
          moduleName: 'stock',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          submenu: [],
        }
    ],
  },

  ,  
        
        {
        path: '',
        title: 'Parmètres',
        moduleName: 'settings',
        iconType: 'material-icons-two-tone',
        icon: 'settings',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [

      {
        path: 'settings/article/add',
        title: 'Articles',
        moduleName: 'settings',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      
        {
          path: 'settings/type/add',
          title: 'Types',//
          moduleName: 'settings',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          submenu: [],
        },
        
        {
          path: 'settings/family/add',
          title: 'Familles',
          moduleName: 'settings',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          submenu: [],
        },
        {
          path: 'settings/category/add',
          title: 'Catégories',
          moduleName: 'settings',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          submenu: [],
        },
        {
          path: 'settings/depot/add',
          title: 'Dépôts',
          moduleName: 'settings',
          iconType: '',
          icon: '',
          class: 'ml-menu',
          groupTitle: false,
          badge: '',
          badgeClass: '',
          submenu: [],
        },
      
     
    ],
  },
  
];
